//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int id { get; set; }
        public Nullable<int> hn_article_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime create_datetime { get; set; }
        public int score { get; set; }
        public int num_comments { get; set; }
        public string url { get; set; }
        public string top_comment_text { get; set; }
        public string semantic_summary { get; set; }
        public string tags { get; set; }
    }
}
